@extends('layouts.app')

@section('title', $vehicle->name.' | TourLink')
@section('content')
<section class="bg-lagoon py-10 text-white"><div class="container-page"><a class="text-xs font-bold text-white/70 hover:text-white" href="{{ route('vehicles.index') }}">Vehicles / {{ $vehicle->location }}</a><h1 class="display mt-8 max-w-3xl text-4xl font-bold sm:text-6xl">{{ $vehicle->name }}</h1><p class="mt-4 text-sm text-white/70">{{ $vehicle->make }} {{ $vehicle->model }} · {{ $vehicle->location }}</p></div></section>
<section class="container-page grid gap-10 py-10 lg:grid-cols-[1.5fr_.7fr]">
    <div class="min-w-0">@if($vehicle->images->isNotEmpty())<div class="grid gap-3 sm:grid-cols-2">@foreach($vehicle->images as $image)<img class="h-64 w-full rounded-2xl object-cover {{ $loop->first ? 'sm:col-span-2 sm:h-[430px]' : '' }}" src="{{ $image->url }}" alt="{{ $image->alt ?? $vehicle->name }}" loading="lazy">@endforeach</div>@endif
        <section class="mt-8"><h2 class="text-2xl font-black text-ink">Vehicle details</h2><dl class="mt-5 grid grid-cols-2 gap-4 rounded-2xl bg-white p-6 shadow-soft sm:grid-cols-3">@foreach(['Body type' => $vehicle->body_type, 'Year' => $vehicle->year, 'Seats' => $vehicle->seating_capacity, 'Transmission' => $vehicle->transmission, 'Fuel' => $vehicle->fuel_type, 'Air conditioning' => $vehicle->air_conditioning ? 'Yes' : 'No'] as $label => $value)<div><dt class="text-xs font-bold text-slate-400">{{ $label }}</dt><dd class="mt-1 text-sm font-extrabold text-ink">{{ $value }}</dd></div>@endforeach</dl></section>
        @if($vehicle->destination)<p class="mt-6 text-sm text-slate-600">Available near {{ $vehicle->destination->name }}.</p>@endif
        <p class="mt-5 text-xs text-slate-500">Registration details are shared with confirmed booking participants.</p>
    </div>
    <aside class="h-fit rounded-2xl bg-white p-6 shadow-soft lg:sticky lg:top-24"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Daily rate</p><p class="mt-1 text-3xl font-black text-ink">KES {{ number_format($vehicle->price_per_day) }}</p><div class="mt-5 flex flex-wrap gap-2 text-xs font-semibold text-slate-500"><span class="rounded-full bg-mist px-3 py-2">{{ $vehicle->seating_capacity }} seats</span>@if($vehicle->four_by_four)<span class="rounded-full bg-mist px-3 py-2">4×4</span>@endif @if($vehicle->driver_included)<span class="rounded-full bg-mist px-3 py-2">Driver included</span>@endif</div><form class="mt-6 grid gap-3 border-t border-slate-100 pt-5" method="POST" action="{{ route('bookings.vehicles.store') }}">@csrf<input type="hidden" name="vehicle" value="{{ $vehicle->id }}"><label class="text-xs font-bold text-slate-500">Pickup date<input class="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" type="date" name="start_date" required></label><label class="text-xs font-bold text-slate-500">Return date<input class="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" type="date" name="end_date" required></label><label class="flex items-center gap-2 text-sm font-bold text-slate-600"><input type="checkbox" name="driver_required" value="1"> Include a driver</label><button class="rounded-xl bg-sun px-4 py-3 text-sm font-extrabold text-ink" type="submit">Request this vehicle</button></form><div class="mt-6 border-t border-slate-100 pt-5"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Vehicle owner</p><p class="mt-1 font-extrabold text-ink">{{ $vehicle->owner?->vehicleOwnerProfile?->business_name ?? $vehicle->owner?->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $vehicle->owner?->verification_level?->value ?? 'BASIC' }}</p></div></aside>
</section>
@endsection
<div>
    <!-- Act only according to that maxim whereby you can, at the same time, will that it should become a universal law. - Immanuel Kant -->
</div>
