@extends('layouts.app')

@section('title', $trip->name.' | TourLink')
@section('content')
<section class="bg-ink py-10 text-white"><div class="container-page"><a class="text-xs font-bold text-white/70 hover:text-white" href="{{ route('trips.index') }}">Trips / {{ $trip->destination?->name }}</a><p class="eyebrow mt-8 text-sun">{{ $trip->category?->name }}</p><h1 class="display mt-2 max-w-3xl text-4xl font-bold sm:text-6xl">{{ $trip->name }}</h1><p class="mt-4 text-sm text-white/70">{{ $trip->starting_point }} → {{ $trip->ending_point }} · {{ $trip->duration_days }} days</p></div></section>
<section class="container-page grid gap-10 py-10 lg:grid-cols-[1.5fr_.7fr]">
    <div class="min-w-0">
        <x-offline-favorite :trip="$trip" />
        @if($trip->images->isNotEmpty())<div class="grid gap-3 sm:grid-cols-2">@foreach($trip->images as $image)<img class="h-64 w-full rounded-2xl object-cover {{ $loop->first ? 'sm:col-span-2 sm:h-[430px]' : '' }}" src="{{ $image->url }}" alt="{{ $image->alt ?? $trip->name }}" width="1200" height="800" decoding="async" @if($loop->first)fetchpriority="high"@else loading="lazy"@endif>@endforeach</div>@endif
        <div class="prose prose-slate mt-8 max-w-none"><h2 class="text-2xl font-black text-ink">About this trip</h2><p class="text-sm leading-7 text-slate-600">{{ $trip->description }}</p></div>
        @if(is_array($trip->itinerary) && $trip->itinerary !== [])<section class="mt-9"><h2 class="text-2xl font-black text-ink">Itinerary</h2><ol class="mt-5 grid gap-3">@foreach($trip->itinerary as $day)<li class="rounded-xl border border-slate-200 bg-white p-5"><p class="text-xs font-extrabold uppercase tracking-wider text-lagoon">Day {{ $day['day'] ?? $loop->iteration }}</p><h3 class="mt-1 font-extrabold text-ink">{{ $day['title'] ?? '' }}</h3><p class="mt-2 text-sm leading-6 text-slate-600">{{ $day['detail'] ?? '' }}</p></li>@endforeach</ol></section>@endif
        <div class="mt-9 grid gap-6 sm:grid-cols-2"><div><h2 class="font-extrabold text-ink">Included</h2><ul class="mt-3 grid gap-2 text-sm text-slate-600">@foreach($trip->included_items ?? [] as $item)<li>✓ {{ $item }}</li>@endforeach</ul></div><div><h2 class="font-extrabold text-ink">Not included</h2><ul class="mt-3 grid gap-2 text-sm text-slate-600">@foreach($trip->excluded_items ?? [] as $item)<li>· {{ $item }}</li>@endforeach</ul></div></div>
        <section class="mt-9"><h2 class="font-extrabold text-ink">Cancellation policy</h2><p class="mt-2 text-sm leading-6 text-slate-600">{{ $trip->cancellation_policy }}</p></section>
    </div>
    <aside class="h-fit rounded-2xl bg-white p-6 shadow-soft lg:sticky lg:top-24"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Price per person</p><p class="mt-1 text-3xl font-black text-ink">KES {{ number_format($trip->price_per_person) }}</p><p class="mt-3 text-sm text-slate-500">{{ $trip->available_seats }} seats available · Departs {{ $trip->departure_date->timezone(config('app.display_timezone'))->format('M j, Y') }}</p><form class="mt-6 grid gap-3 border-t border-slate-100 pt-5" method="POST" action="{{ route('bookings.trips.store') }}">@csrf<input type="hidden" name="trip" value="{{ $trip->id }}"><label class="text-xs font-bold text-slate-500">Travelers<input class="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" type="number" name="travelers" min="1" max="{{ min(100, $trip->available_seats) }}" value="1" required></label><label class="text-xs font-bold text-slate-500">Pickup location<input class="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" type="text" name="pickup_location" maxlength="120"></label><input type="hidden" name="start_date" value="{{ $trip->departure_date->toDateTimeString() }}"><button class="rounded-xl bg-sun px-4 py-3 text-sm font-extrabold text-ink" type="submit">Request this trip</button></form><div class="mt-6 border-t border-slate-100 pt-5"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Hosted by</p><p class="mt-1 font-extrabold text-ink">{{ $trip->operator?->operatorProfile?->company_name ?? $trip->operator?->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $trip->operator?->verification_level?->value ?? 'BASIC' }}</p></div></aside>
</section>
@endsection
<div>
    <!-- Breathing in, I calm body and mind. Breathing out, I smile. - Thich Nhat Hanh -->
</div>
