@extends('layouts.vehicle-owner')
@section('title', 'Vehicle-owner profile | TourLink')
@section('content')
<div class="mx-auto max-w-3xl space-y-6 p-4 sm:p-8"><div><p class="text-xs font-black uppercase tracking-widest text-emerald-800">Owner profile</p><h1 class="mt-2 text-3xl font-black">Build trust with travelers</h1></div><form method="POST" action="{{ route('vehicle-owner.profile.update') }}" class="grid gap-4 rounded border border-slate-200 bg-white p-6">@csrf @method('PUT')<label class="grid gap-1 text-sm font-semibold">Business name<input required name="business_name" value="{{ old('business_name', $profile->business_name) }}" class="min-h-11 rounded border border-slate-300 px-3"></label><label class="grid gap-1 text-sm font-semibold">About your business<textarea name="description" rows="5" class="rounded border border-slate-300 p-3">{{ old('description', $profile->description) }}</textarea></label><button class="w-fit rounded bg-emerald-800 px-6 py-3 text-sm font-bold text-white">Save profile</button></form><form method="POST" action="{{ route('vehicle-owner.verification.store') }}" enctype="multipart/form-data" class="grid gap-4 rounded border border-amber-200 bg-amber-50 p-6">@csrf<h2 class="font-black">Request verification</h2>
    @if($verificationRequest->exists)<p class="text-sm font-bold text-amber-900">Current status: <span class="uppercase">{{ str($verificationRequest->status->value)->replace('_', ' ')->title() }}</span></p>@endif
    <div class="grid gap-4 sm:grid-cols-2">
        <label class="grid gap-1 text-sm font-semibold">Vehicle logbook<span class="text-xs font-normal text-slate-600">PDF, JPG or PNG, up to 5 MB. Required before approval.</span><input type="file" name="documents[logbook]" accept=".pdf,image/jpeg,image/png" class="rounded border border-amber-300 bg-white p-2 text-sm file:mr-3 file:rounded file:border-0 file:bg-amber-800 file:px-3 file:py-1.5 file:text-xs file:font-bold file:text-white"></label>
        <label class="grid gap-1 text-sm font-semibold">KRA PIN certificate<span class="text-xs font-normal text-slate-600">Your Kenya Revenue Authority PIN certificate. Required before approval.</span><input type="file" name="documents[kra_pin]" accept=".pdf,image/jpeg,image/png" class="rounded border border-amber-300 bg-white p-2 text-sm file:mr-3 file:rounded file:border-0 file:bg-amber-800 file:px-3 file:py-1.5 file:text-xs file:font-bold file:text-white"></label>
    </div>
    @if($verificationRequest->documents)<ul class="grid gap-1 text-xs text-slate-700">@foreach($verificationRequest->documents as $document)<li><span class="font-bold">{{ $document['label'] ?? str($document['key'] ?? 'Document')->headline() }}:</span> {{ $document['original_name'] ?? 'Uploaded' }}@if(!empty($document['size'])) ({{ number_format($document['size'] / 1024, 0) }} KB)@endif</li>@endforeach</ul>@endif
    <textarea name="notes" rows="3" maxlength="2000" placeholder="Add license, insurance, or ownership details" class="rounded border border-amber-300 bg-white p-3">{{ old('notes', $verificationRequest->notes) }}</textarea><button class="w-fit rounded bg-amber-800 px-5 py-3 text-sm font-bold text-white">Submit request</button></form></div>
@endsection
