@extends('layouts.operator')
@section('title', ($trip->exists ? 'Edit trip' : 'Create trip').' | Havenedge Tourlink')
@section('content')
<div class="mx-auto max-w-5xl space-y-6 p-4 sm:p-8">
    <div><p class="text-xs font-black uppercase tracking-widest text-emerald-800">Trip management</p><h1 class="mt-2 text-3xl font-black">{{ $trip->exists ? 'Edit trip' : 'Create trip' }}</h1><p class="mt-2 text-sm text-slate-600">Trips are reviewed before they can be published.</p></div>
    <form method="POST" action="{{ $trip->exists ? route('operator.trips.update', $trip) : route('operator.trips.store') }}" enctype="multipart/form-data" class="grid gap-6">
        @csrf @if($trip->exists) @method('PUT') @endif
        <section class="grid gap-4 rounded border border-slate-200 bg-white p-5 sm:grid-cols-2">
            <h2 class="sm:col-span-2 text-lg font-black">Trip basics</h2>
            @foreach([['name','Trip name',$trip->name],['starting_point','Starting point',$trip->starting_point],['ending_point','Ending point',$trip->ending_point]] as [$name,$label,$value])<label class="grid gap-1 text-sm font-semibold">{{ $label }}<input required name="{{ $name }}" value="{{ old($name, $value) }}" class="min-h-11 rounded border border-slate-300 px-3"></label>@endforeach
            <label class="grid gap-1 text-sm font-semibold sm:col-span-2">Description<textarea required name="description" rows="4" class="rounded border border-slate-300 p-3">{{ old('description', $trip->description) }}</textarea></label>
            <label class="grid gap-1 text-sm font-semibold">Destination<select required name="destination_id" class="min-h-11 rounded border border-slate-300 px-3"><option value="">Select</option>@foreach($destinations as $destination)<option value="{{ $destination->id }}" @selected(old('destination_id', $trip->destination_id) === $destination->id)>{{ $destination->name }}</option>@endforeach</select></label>
            <label class="grid gap-1 text-sm font-semibold">Category<select required name="category_id" class="min-h-11 rounded border border-slate-300 px-3"><option value="">Select</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $trip->category_id) === $category->id)>{{ $category->name }}</option>@endforeach</select></label>
        </section>
        <section class="grid gap-4 rounded border border-slate-200 bg-white p-5 sm:grid-cols-2">
            <h2 class="sm:col-span-2 text-lg font-black">Price, dates, and seats</h2>
            @foreach([['duration_days','Duration (days)',1],['price_per_person','Price per traveler',0],['max_travelers','Maximum travelers',1],['min_travelers','Minimum travelers',1],['available_seats','Available seats',0]] as [$name,$label,$default])<label class="grid gap-1 text-sm font-semibold">{{ $label }}<input required type="number" min="0" name="{{ $name }}" value="{{ old($name, $trip->{$name} ?: $default) }}" class="min-h-11 rounded border border-slate-300 px-3"></label>@endforeach
            <label class="grid gap-1 text-sm font-semibold">Departure date<input required type="datetime-local" name="departure_date" value="{{ old('departure_date', $trip->departure_date?->format('Y-m-d\TH:i')) }}" class="min-h-11 rounded border border-slate-300 px-3"></label>
            <label class="grid gap-1 text-sm font-semibold">Return date<input required type="datetime-local" name="return_date" value="{{ old('return_date', $trip->return_date?->format('Y-m-d\TH:i')) }}" class="min-h-11 rounded border border-slate-300 px-3"></label>
            <label class="grid gap-1 text-sm font-semibold sm:col-span-2">Pickup points <span class="font-normal text-slate-500">One per line</span><textarea required name="pickup_points" rows="3" class="rounded border border-slate-300 p-3">{{ old('pickup_points', implode("\n", $trip->pickup_points ?? [])) }}</textarea></label>
        </section>
        <section class="grid gap-4 rounded border border-slate-200 bg-white p-5"><h2 class="text-lg font-black">Availability schedule</h2><p class="text-sm text-slate-500">Set the seats available for this departure. Add more schedule rows as needed.</p><div class="grid gap-3 sm:grid-cols-2"><label class="grid gap-1 text-sm font-semibold">Date<input type="date" name="availability[0][date]" value="{{ old('availability.0.date', $trip->availabilities->first()?->date?->format('Y-m-d')) }}" class="min-h-11 rounded border border-slate-300 px-3"></label><label class="grid gap-1 text-sm font-semibold">Seats<input type="number" min="0" name="availability[0][seats]" value="{{ old('availability.0.seats', $trip->availabilities->first()?->seats ?? $trip->available_seats) }}" class="min-h-11 rounded border border-slate-300 px-3"></label></div></section>
        <section class="grid gap-4 rounded border border-slate-200 bg-white p-5">
            <h2 class="text-lg font-black">Experience details</h2>
            <label class="grid gap-1 text-sm font-semibold">Itinerary JSON <span class="font-normal text-slate-500">Example: [{"day":1,"title":"Arrival","detail":"Airport transfer"}]</span><textarea required name="itinerary" rows="5" class="rounded border border-slate-300 p-3">{{ old('itinerary', json_encode($trip->itinerary ?? [['day' => 1, 'title' => '', 'detail' => '']], JSON_PRETTY_PRINT)) }}</textarea></label>
            @foreach([['accommodation','Accommodation',false],['transport','Transport',false],['meals','Meals (one per line)',true],['activities','Activities (one per line)',true],['included_items','Included (one per line)',true],['excluded_items','Excluded (one per line)',true],['cancellation_policy','Cancellation policy',false]] as [$name,$label,$list])<label class="grid gap-1 text-sm font-semibold">{{ $label }}<textarea {{ $name === 'cancellation_policy' ? 'required' : '' }} name="{{ $name }}" rows="{{ $name === 'cancellation_policy' ? 4 : 2 }}" class="rounded border border-slate-300 p-3">{{ old($name, $list ? implode("\n", $trip->{$name} ?? []) : $trip->{$name}) }}</textarea></label>@endforeach
        </section>
        <section class="grid gap-4 rounded border border-slate-200 bg-white p-5"><h2 class="text-lg font-black">Trip images</h2><p class="text-sm text-slate-500">Upload up to 12 images or provide public URLs.</p><input type="file" name="images_files[]" accept="image/*" multiple class="rounded border border-slate-300 p-2"><textarea name="image_urls" rows="3" placeholder="One public image URL per line" class="rounded border border-slate-300 p-3">{{ old('image_urls', $trip->images->pluck('url')->implode("\n")) }}</textarea></section>
        <div class="flex justify-end gap-3"><a href="{{ route('operator.trips.index') }}" class="rounded border border-slate-300 px-5 py-3 text-sm font-bold">Cancel</a><button class="rounded bg-emerald-800 px-6 py-3 text-sm font-bold text-white">Save trip</button></div>
    </form>
    @if($trip->exists)<form method="POST" action="{{ route('operator.trips.delete', $trip) }}" onsubmit="return confirm('Archive this trip?')">@csrf @method('DELETE')<button class="text-sm font-bold text-red-700">Delete trip</button></form>@endif
</div>
@endsection
