@extends('layouts.app')

@section('title', 'Travel journal | Havenedge Tourlink')
@section('content')
<section class="bg-lagoon py-12 text-white sm:py-16"><div class="container-page"><p class="eyebrow text-sun">Travel journal</p><h1 class="display mt-2 text-4xl font-bold sm:text-6xl">Stories for the road.</h1><form method="GET" action="{{ route('blog.index') }}" class="mt-8 flex max-w-xl gap-2"><label class="sr-only" for="blog-search">Search articles</label><input id="blog-search" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search articles..." class="min-h-11 flex-1 rounded-lg border border-white/25 bg-white/10 px-4 text-sm text-white placeholder:text-white/60 focus:border-sun focus:outline-none"><button type="submit" class="min-h-11 rounded-lg bg-sun px-5 text-sm font-extrabold text-ink">Search</button></form></div></section>
<section class="container-page min-h-[55vh] py-10"><div class="mb-7 flex items-center justify-between"><p class="text-sm text-slate-500">{{ $posts->total() }} {{ Str::plural('article', $posts->total()) }}</p>@if(!empty($filters['search']))<a class="text-xs font-bold text-lagoon" href="{{ route('blog.index') }}">Clear search</a>@endif</div>
    @if($posts->isEmpty())<div class="grid place-items-center rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><h2 class="font-extrabold text-ink">No articles match that search</h2><p class="mt-2 max-w-sm text-sm leading-6 text-slate-500">Try a different word, or browse everything we have published so far.</p><a class="mt-5 rounded-full bg-ink px-5 py-3 text-xs font-extrabold text-white" href="{{ route('blog.index') }}">Browse all articles</a></div>@else<div class="grid gap-5 md:grid-cols-2 lg:grid-cols-3">@foreach($posts as $post)<article class="flex flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">@if($post->image_url)<img src="{{ $post->image_url }}" alt="{{ $post->title }}" class="h-44 w-full object-cover" loading="lazy">@endif<div class="flex flex-1 flex-col p-5"><p class="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">{{ $post->created_at?->format('j M Y') }}</p><h2 class="mt-2 text-lg font-extrabold text-ink"><a class="hover:text-lagoon" href="{{ route('blog.show', ['blogPost' => $post->slug]) }}">{{ $post->title }}</a></h2><p class="mt-2 text-sm leading-6 text-slate-600">{{ $post->excerpt }}</p><span class="mt-4 text-xs font-extrabold text-lagoon">Read article &rarr;</span></div></article>@endforeach</div><div class="mt-9">{{ $posts->links() }}</div>@endif
</section>
@endsection
