@extends('layouts.admin')

@section('title', 'Blog | Havenedge Tourlink Admin')

@section('content')
    <div class="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
        <header class="flex flex-wrap items-end justify-between gap-4 border-b border-slate-200 pb-6"><div><p class="text-xs font-bold uppercase tracking-wider text-emerald-800">Content</p><h1 class="mt-2 text-3xl font-black text-slate-950">Blog</h1><p class="mt-1 text-sm text-slate-600">Draft, edit and publish Havenedge Tourlink stories.</p></div><a href="{{ route('admin.blog.create') }}" class="rounded bg-emerald-800 px-5 py-3 text-sm font-bold text-white">New post</a></header>
        @if(session('status'))<p role="status" class="mt-5 border-l-4 border-emerald-700 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-950">{{ session('status') }}</p>@endif
        <form method="GET" class="mt-6 flex flex-wrap gap-3 border-b border-slate-200 pb-5"><label class="sr-only" for="blog-search">Search posts</label><input id="blog-search" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search title or slug" class="min-h-10 w-full max-w-md rounded border border-slate-300 px-3 text-sm"><label class="sr-only" for="blog-published">Publication</label><select id="blog-published" name="published" class="min-h-10 rounded border border-slate-300 bg-white px-3 text-sm"><option value="">All states</option><option value="1" @selected(($filters['published'] ?? '') === true || ($filters['published'] ?? '') === '1')>Published</option><option value="0" @selected(($filters['published'] ?? '') === false || ($filters['published'] ?? '') === '0')>Draft</option></select><button class="min-h-10 rounded border border-slate-300 px-4 text-sm font-bold">Filter</button><a href="{{ route('admin.blog.index') }}" class="grid min-h-10 place-items-center text-sm text-slate-600">Clear</a></form>
        <div class="mt-2 overflow-x-auto"><table class="w-full min-w-[780px] text-left text-sm"><thead class="border-b border-slate-200 text-xs font-bold uppercase text-slate-500"><tr><th class="py-3 pr-4">Post</th><th class="py-3 pr-4">Slug</th><th class="py-3 pr-4">Updated</th><th class="py-3 pr-4">Status</th><th class="py-3">Actions</th></tr></thead><tbody>@forelse($posts as $post)<tr class="border-b border-slate-100"><td class="py-4 pr-4"><a href="{{ route('admin.blog.edit', $post) }}" class="font-bold text-slate-950 hover:underline">{{ $post->title }}</a><p class="mt-1 max-w-xl truncate text-xs text-slate-500">{{ $post->excerpt }}</p></td><td class="py-4 pr-4 text-xs text-slate-600">{{ $post->slug }}</td><td class="py-4 pr-4">{{ $post->created_at?->format('M j, Y') }}</td><td class="py-4 pr-4">{{ $post->published ? 'Published' : 'Draft' }}</td><td class="py-4"><div class="flex gap-3"><a href="{{ route('admin.blog.edit', $post) }}" class="font-bold text-emerald-800">Edit</a><form method="POST" action="{{ route('admin.blog.publish', $post) }}">@csrf @method('PATCH')<button class="font-bold text-slate-600">{{ $post->published ? 'Unpublish' : 'Publish' }}</button></form></div></td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-sm text-slate-600">No blog posts found.</td></tr>@endforelse</tbody></table></div>
        <div class="mt-6">{{ $posts->links() }}</div>
    </div>
@endsection